<?php
// Ensure you have the order object
$order = $block->getOrder();

// Check if the order status is 'complete'
$overrideTotalDue = $order->getStatus() == 'processing' || $order->getStatus() == 'complete';
?>

<table class="data-table admin__table-secondary order-subtotal-table">
    <?php $_totals = $block->getTotals('footer'); ?>
    <?php if ($_totals): ?>
        <?php foreach ($_totals as $index => $_total): ?>
            <?php if ($index === 3 && $overrideTotalDue): ?>
                <!-- Override the display of Total Due -->
                <tr class="col-total-due-override">
                    <td <?= /* @noEscape */ $block->getLabelProperties() ?> class="label">
                        <strong>
                            <?= $block->escapeHtml($_total->getLabel()) ?>
                        </strong>
                    </td>
                    <td <?= /* @noEscape */ $block->getValueProperties() ?>>
                        <strong>
                            <?= $order->formatPrice(0); ?>
                        </strong>
                    </td>
                </tr>
            <?php else: ?>
                <tr class="col-<?= $block->escapeHtmlAttr($index) ?>">
                    <td <?= /* @noEscape */ $block->getLabelProperties() ?> class="label">
                        <strong>
                            <?= $block->escapeHtml($_total->getLabel()) ?>
                        </strong>
                    </td>
                    <td <?= /* @noEscape */ $block->getValueProperties() ?>>
                        <strong>
                            <?= $order->formatPrice($_total->getValue()); ?>
                        </strong>
                    </td>
                </tr>
            <?php endif; ?>
        <?php endforeach; ?>
    <?php endif; ?>
</table>